config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#root'

  resources :bundles

  namespace :api do
    namespace :v1 do
      jsonapi_resources :bundles
      jsonapi_resources :products
      jsonapi_resources :subscription_periods
    end
  end
end

app/models/bundle.rb
class Bundle < ApplicationRecord
  has_many :offers

  validates :name, presence: true

  def add_item(*args)
    item = BundleItem.new(*args)
    items_json[item.product.code] = item.subscription_period.code
    self
  end

  def add_item!(product, period)
    add_item(product, period).tap(&:save!)
  end

  def set_items(items)
    items_json.clear
    items.each { |item| add_item(item) }
    save!
  end

  def items
    items_json.map do |product_code, period_code|
      BundleItem.new(product_code, period_code)
    end
  end
  alias_method :bundle_items, :items

  def default_offer
    offer = offers.create_with(price: price).find_or_create_by!(segment: nil)
    offer.update!(price: price) unless offer.price == price
    offer
  end

  def permanent_offers
    offers.select(&:permanent?)
  end

  def test_offers
    offers.select(&:test?)
  end

  # noinspection RailsChecklist04
  def find_offer(student)
    offers_in_order = test_offers + permanent_offers.select(&:segment)
    offers_in_order.find { |o| o.matches?(student) } || default_offer
  end

  def create_order(student)
    offer = find_offer(student)
    Order.create!(offer: offer, student: student)
  end
end

app/controllers/api/v1/bundles_controller.rb
class Api::V1::BundlesController < Api::V1::BaseController
end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  before_action :set_bundle, only: [:show, :edit, :update, :destroy]

  # GET /bundles
  def index
    @bundles = Bundle.all
  end

  # GET /bundles/1
  def show
  end

  # GET /bundles/new
  def new
    @bundle = Bundle.new
  end

  # GET /bundles/1/edit
  def edit
  end

  # POST /bundles
  def create
    @bundle = Bundle.new(bundle_params)

    respond_to do |format|
      if @bundle.save
        format.html { redirect_to @bundle, notice: 'Bundle was successfully created.' }
        # format.json { render :show, status: :created, location: @bundle }
      else
        format.html { render :new }
        # format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bundles/1
  def update
    respond_to do |format|
      if @bundle.update(bundle_params)
        format.html { redirect_to @bundle, notice: 'Bundle was successfully updated.' }
        # format.json { render :show, status: :ok, location: @bundle }
      else
        format.html { render :edit }
        # format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bundles/1
  def destroy
    @bundle.destroy
    respond_to do |format|
      format.html { redirect_to bundles_url, notice: 'Bundle was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bundle
      @bundle = Bundle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bundle_params
      params.require(:bundle).permit(:name, :price)
    end
end

app/views/bundles/_form.html.slim
= form_for @bundle, html: { class: "form form-horizontal bundle" } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :items_json, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :items_json, :class => 'form-control'
    = f.error_span(:items_json)
  .form-group
    = f.label :price, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :price, :class => 'form-control'
    = f.error_span(:price)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), bundles_path, :class => 'btn'

app/views/bundles/edit.html.slim
- model_class = Bundle
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bundles/index.html.slim
- model_class = Bundle
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:items_json)
      th= model_class.human_attribute_name(:price)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @bundles.each do |bundle|
      tr
        td= link_to bundle.id, bundle_path(bundle)
        td= bundle.name
        td= bundle.items_json
        td= bundle.price
        td
          = link_to t('.show', :default => t("helpers.links.show")), bundle_path(bundle), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_bundle_path(bundle), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), bundle_path(bundle), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_bundle_path, :class => 'btn btn-primary'

app/views/bundles/new.html.slim
- model_class = Bundle
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bundles/show.html.slim
- model_class = Bundle
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @bundle.name
p
  strong= model_class.human_attribute_name(:items_json) + ':'
  br
  = @bundle.items_json
p
  strong= model_class.human_attribute_name(:price) + ':'
  br
  = @bundle.price

= link_to t('.back', :default => t("helpers.links.back")), bundles_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_bundle_path(@bundle), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), bundle_path(@bundle), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'